# Generated by Django 2.0.4 on 2018-04-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20180426_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='title',
            new_name='name',
        ),
    ]
